from .schoolinfo import *
from .about_models import *
from .gallery_models import *
from .fees_structure import *
from .contact_us import *
from .facilities_m import *
from .slider_models import *
from .license_models import *
from .admission_m import *
from .staff_models import *
