# Generated by Django 5.2.11 on 2026-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('management_name', models.CharField(max_length=150)),
                ('management_title', models.CharField(max_length=150)),
                ('management_message', models.TextField()),
                ('management_photo', models.ImageField(upload_to='management/')),
                ('principal_name', models.CharField(max_length=150)),
                ('principal_title', models.CharField(max_length=150)),
                ('principal_message', models.TextField()),
                ('principal_photo', models.ImageField(upload_to='principal/')),
            ],
        ),
    ]
