# Generated by Django 5.2.11 on 2026-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_album_gallerycategory_albumimage_album_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
