# Generated by Django 5.2.11 on 2026-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_schoolsettings_email_schoolsettings_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='phone_number',
            field=models.CharField(default='9111215500', max_length=15),
        ),
    ]
