# Generated by Django 5.2.11 on 2026-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
    ]
