# Generated by Django 5.2.11 on 2026-03-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feeheader_schoolclass_term_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed', models.TextField()),
            ],
        ),
    ]
