# Generated by Django 5.2.11 on 2026-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_schoolsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolSetting',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='map_embed',
            field=models.TextField(null='True, blank=True'),
            preserve_default='True, blank=True',
        ),
    ]
