# Generated by Django 5.2.11 on 2026-03-06 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_contactmessage_delete_schoolsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='address',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='map_embed',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='map_embed',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
