# Generated by Django 5.2.11 on 2026-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_schoolmap_rename_address_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('features', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
