# Generated by Django 5.2.11 on 2026-03-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_emailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='term_type',
        ),
    ]
