# Generated by Django 5.2.11 on 2026-03-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettingsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolSettings',
        ),
    ]
