# Generated by Django 6.0.2 on 2026-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_schoolsettingsinfo_delete_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettingsinfo',
            name='address',
            field=models.TextField(blank=True, default='Ripur CG', null=True),
        ),
    ]
