# Generated by Django 6.0.2 on 2026-03-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_admissionapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionapplication',
            options={},
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='updated_at',
        ),
    ]
