# Generated by Django 6.0.3 on 2026-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_staffleave_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
