from .auth import *
from .aboutus import *
from .gallery_views import *
from .fees_views import *
from .contact_views import *
from .facility_views import *
from .slider_views import *
from .school_setting import *
from .license_views import *
from .admission_v import *
from .staff_views import *